[CREATED] '상품보기' 페이지를 위한 get 메소드 구현
wecode-bootcamp-korea/27-1st-weasley-backend pull request #20
Opened 2021-12-03 10:11 UTC by bakha1002

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- '상품보기' 페이지에서 쓰일 데이터 프론트단에서 쓸 수 있도록 view 작성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. CategoryView 작성
- 프론트단에서 필요한 데이터만 db에서 가져올 수 있게 로직 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 정참조, 역참조 개념을 미숙하게나마 이해하게 되었습니다.

<br />

## :: 기타 질문 및 특이 사항

2021-12-06 02:57 UTC, lordmyshepherd requested changes

2021-12-06 02:57 UTC, lordmyshepherd commented on products/views.py
> +        return JsonResponse({'MESSAGE': 'SUCCESS', 'RESULT': category_data}, status=200)
깔끔하게 잘 구현해 주셨네요!
1. 카테고리 목록을 반환하는 경우에는 class명을 복수로 만들어주세요~
2. 변수명을 정할 때 data라는 용어는 제외해도 좋겠습니다.

```suggestion
class CategoriesView(View):
    def get(self, request):
        categories = [{
            'name' : category.name,
            'ml_volume'     : category.ml_volume,
            'price'         : category.price,
            'products'      : [{
                'thumb' : product.image_set.get(name='thumb').url,
                'tags'  : [i.name for i in product.tags.all()],
                'id'    : product.id
            } for product in category.product_set.all()]
        } for category in Category.objects.all()]

        return JsonResponse({'MESSAGE': 'SUCCESS', 'RESULT': categories}, status=200) 
```

2021-12-06 04:08 UTC, bakha1002 commented on products/views.py
> +        return JsonResponse({'MESSAGE': 'SUCCESS', 'RESULT': category_data}, status=200)
수정했습니당!

2021-12-06 08:02 UTC, lordmyshepherd requested changes

2021-12-06 08:02 UTC, lordmyshepherd commented on products/views.py
> +class CategoriesView(View):
아래와 같이 offset, limit으로 받을 수 있도록 구현해 주셔야합니다.
```python
8000/products?offset=0&limit=100
```

2021-12-06 08:02 UTC, lordmyshepherd commented on products/views.py
> +class CategoriesView(View):
추가로 limit에는 default value를 설정해 주셔야 합니다.
예) 100개

2021-12-06 11:09 UTC, bakha1002 commented on products/views.py
> +class CategoriesView(View):
수정사항 반영했습니다!

2021-12-07 01:19 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2021-12-07 01:19 UTC, merged